# Generated by Django 6.0.1 on 2026-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('conference', 'Conférence'), ('concert', 'Concert'), ('sport', 'Sport'), ('workshop', 'Atelier'), ('festival', 'Festival'), ('other', 'Autre')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('location', models.CharField(max_length=300, verbose_name='Lieu')),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='France', max_length=100)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité totale')),
                ('available_seats', models.PositiveIntegerField(verbose_name='Places disponibles')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_date'],
            },
        ),
    ]
